Apps/Ajustes/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import inicio, ElementosView, nuevo_elemento, nuevo_producto, ProductoView
from .views import origen

urlpatterns = [
    url(r'^inicio/', inicio, name='inicio'),
    url(r'^elementos/', login_required(ElementosView.as_view()), name='elementos'),
    url(r'^nuevo-elemento', nuevo_elemento, name='nuevo_elemento'),
    url(r'^nuevo-producto', nuevo_producto, name='nuevo_producto'),
    url(r'^productos', ProductoView.as_view(), name='productos'),
    url(r'^origen/(?P<id>\w+)', origen, name='p_p')
]

Apps/Soporte/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import IncidenteView, crear_incidente, crear_incidente_elemento
from .views import crear_solucion, incidente_elemento, solucion_incidente, solucionar_incidente
from .views import ProveedorView, crear_proveedor, crear_marca, MarcaView, editar_marca
from .views import proveedor_marca

urlpatterns = [
    url(r'^incidentes/', login_required(IncidenteView.as_view()), name='incidentes'),
    url(r'^crear-incidente', crear_incidente, name='crear_incidente'),
    url(r'^crear-solucion/(?P<id>\w+)/', crear_solucion, name='crear_solucion'),
    url(r'^incidente/(?P<id_objeto>\w+)/', incidente_elemento, name='incidentes_objeto'),
    url(r'^solucion-incidente/(?P<id_incidente>\w+)/', solucion_incidente, name='solucion_incidente'),
    url(r'^solucionar-incidente/(?P<id_incidente>\w+)/', solucionar_incidente, name='solucionar_incidente'),
    url(r'^incidente-elemento/(?P<id_elemento>\w+)/', crear_incidente_elemento, name='incidente_elemento'),
    url(r'^proveedores/', ProveedorView.as_view(), name='proveedores'),
    url(r'^crear-proveedor', crear_proveedor, name='crear_proveedor'),
    url(r'^crear-marca', crear_marca, name='crear_marca'),
    url(r'^marcas', MarcaView.as_view(), name='marcas'),
    url(r'editar-marca/(?P<id>\w+)/', editar_marca, name='editar_marca'),
    url(r'^asignar-proveedor-marca', proveedor_marca, name='proveedor_marca'),

]

itil/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import logout
from django.shortcuts import redirect
from Apps.Ajustes.views import login


def salir(request):
    logout(request)
    return redirect('log_in')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    #   url de login
    url(r'^$', login, name='log_in'),
    url(r'^login/', login, name='log_in_'),
    url(r'^salir', salir, name='salir'),
    # urls de ajustes
    url(r'^ajustes/', include('Apps.Ajustes.urls', namespace='ajustes')),
    # urls de soporte
    url(r'^soporte/', include('Apps.Soporte.urls', namespace='soporte')),

    url(r'^empleados/', include('Apps.Empleados.urls', namespace='empleado')),

]

Apps/Ajustes/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from smart_selects.db_fields import ChainedForeignKey


class MainModel(models.Model):

    nombre = models.CharField(max_length=50)

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.nombre


class Tipo(MainModel):

    class Meta:
        verbose_name = 'Tipo'
        verbose_name_plural = 'Tipos'


class Departamento(MainModel):

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'


class Cargo(MainModel):

    class Meta:
        verbose_name = 'Cargo'
        verbose_name_plural = 'Cargos'


class Empleado(User):

    cargo = models.ForeignKey(Cargo)
    departamento = models.ForeignKey(Departamento)
    notificaciones = models.PositiveIntegerField(editable=False, default=0)

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

    def __unicode__(self):
        return self.get_full_name()


class Proveedor(MainModel):

    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'


class Marca(MainModel):

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'


class ProveedorMarca(models.Model):

    proveedor_x = models.ForeignKey(Proveedor)
    marca = models.ForeignKey(Marca)

    class Meta:
        verbose_name = 'Proveedor Marca'
        verbose_name_plural = 'Marcas y Proveedores'
        unique_together = ['proveedor_x', 'marca']

    def __unicode__(self):
        return self.marca.nombre


class Producto(models.Model):

    tipo = models.ForeignKey(Tipo)
    proveedor = models.ForeignKey(Proveedor)
    marca = ChainedForeignKey(
        ProveedorMarca,
        chained_field='proveedor',
        chained_model_field='proveedor_x'
    )
    descripcion = models.TextField()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __unicode__(self):
        d = '{0} marca {1} : descripcion {2} : proveedor {3}'
        return d.format(self.tipo, self.marca, self.descripcion, self.proveedor)


class ElementoConfiguracion(models.Model):

    serial = models.CharField(max_length=50, unique=True)
    tipo = models.ForeignKey(Tipo)
    producto = ChainedForeignKey(
        Producto,
        chained_field='tipo',
        chained_model_field='tipo',
    )
    departamento = models.ForeignKey(Departamento)
    usuario = ChainedForeignKey(
        Empleado,
        chained_field='departamento',
        chained_model_field='departamento'
    )
    fecha_configuracion = models.DateField()
    incidentes = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        verbose_name = 'Elemento de Configuracion'
        verbose_name_plural = 'Elementos de Configuracion'
        unique_together = ['tipo', 'producto', 'usuario']

    def __unicode__(self):
        d = '{0} : marca {1} {2} : a cargo del usuario {3}'
        return d.format(self.tipo, self.producto.marca, self.producto.descripcion, self.usuario)

Apps/Ajustes/forms.py
from django import forms
from models import ElementoConfiguracion, Producto


class BaseForm(forms.ModelForm):
    form_title = ''


class ElementoConfiguracionForm(BaseForm):

    form_title = 'Elemento de configuracion'

    class Meta:
        model = ElementoConfiguracion
        fields = ('__all__')
        exclude = ('incidentes',)


class ProductoForm(BaseForm):

    form_title = 'Producto'

    class Meta:
        model = Producto
        fields = ('__all__')

Apps/Ajustes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout, login as auth_login
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.views.generic import ListView
from Apps.Ajustes.forms import ElementoConfiguracionForm, ProductoForm
from Apps.Ajustes.models import Tipo, ElementoConfiguracion, Producto, Proveedor
from Apps.Soporte.models import Incidente


def login(request):
    context = {'error': False}
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                if request.user.is_superuser:
                    return redirect('ajustes:inicio')
                else:
                    return redirect('empleado:incidentes')
            else:
                context = {'msj': 'El usuario ha sido desactivado', 'error': True}
        else:
            context = {'msj': 'Usuario o Password incorrecta', 'error': True}
    return render(request, 'Main/sesion/login.html', context)


@login_required
def inicio(request):
    incidentes = Incidente.objects.filter(cerrado=False).count()
    elementos = ElementoConfiguracion.objects.all().count()
    solucionados = Incidente.objects.all().filter(cerrado=True).count()
    context = {
        'incidentes': incidentes,
        'elementos': elementos,
        'solucionados': solucionados
    }
    return render(request, 'index.html', context)


class ListBase(LoginRequiredMixin, ListView):
    pass


class ElementosView(ListBase):

    model = ElementoConfiguracion
    template_name = 'listados/ajustes/elemento_de_configuracion.html'
    paginate_by = 10
    context_object_name = 'elementos'
    queryset = ElementoConfiguracion.objects.all().order_by('-id')


@login_required
def nuevo_elemento(request):
    form = ElementoConfiguracionForm()
    if request.POST:
        form = ElementoConfiguracionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ajustes:elementos')
    context = {
        'form': form,
        'accion': 'Crear'
    }
    return render(request, 'Main/forms/baseForm.html', context)


@login_required
def nuevo_producto(request):
    form = ProductoForm()
    if request.POST:
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ajustes:productos')
    context = {
        'form': form,
        'accion': 'Crear'
    }
    return render(request, 'Main/forms/baseForm.html', context)


class ProductoView(ListBase):

    template_name = 'listados/ajustes/productos.html'
    model = Producto
    paginate_by = 10
    context_object_name = 'productos'
    queryset = Producto.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(ProductoView, self).get_context_data(**kwargs)
        context['proveedor'] = False
        return context


def origen(request, **kwargs):
    id_proveedor = kwargs.get('id')
    proveedor = Proveedor.objects.get(id=id_proveedor)
    productos = Producto.objects.filter(proveedor_id=proveedor.id)
    return render(request, 'listados/ajustes/productos.html', {
        'proveedor_data': proveedor,
        'productos': productos,
        'proveedor': True
    })

templates/listados/ajustes/elemento_de_configuracion.html
{% extends 'Main/base.html' %}

{% block contenido %}

    <div class="card">
        <div class="card-header">
            <h2>
                Lista de tipos de producto
            </h2>
        </div>

        <div class="table-responsive">
            <table id="data-table-basic" class="table table-striped">
                <thead>
                <tr>
                    <th>Serial</th>
                    <th>Tipo</th>
                    <th>Referencia del Producto</th>
                    <th>Departamento</th>
                    <th>Usuario encargado</th>
                    <th>Fecha de configuracion</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                {% for elemento in elementos %}
                    <tr>
                        <td>{{ elemento.serial }}</td>
                        <td>{{ elemento.tipo }}</td>
                        <td>{{ elemento.producto.descripcion }} </td>
                        <td>{{ elemento.departamento }}</td>
                        <td>{{ elemento.usuario }}</td>
                        <td>{{ elemento.fecha_configuracion }}</td>
                        <td>
                            <a href="{% url 'soporte:incidentes_objeto' elemento.id %}"
                               class="btn bgm-teal waves-effect">
                                ver incidentes <i class="zmdi zmdi-eye"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    <a href="{% url 'ajustes:nuevo_elemento' %}"
       class="btn btn-float btn-success m-btn waves-effect waves-circle waves-float">
        <i class="zmdi zmdi-plus"></i>
    </a>

    {% if is_paginated %}
        {% include 'Main/paginator.html' %}
    {% endif %}

{% endblock %}

templates/listados/ajustes/productos.html
{% extends 'Main/base.html' %}

{% block contenido %}

    <div class="card">
        <div class="card-header">
            <h2>
                Lista de productos
                {% if proveedor %}
                    del proveedor <span style="color: black">{{ proveedor_data.nombre }}</span>
                {% endif %}
            </h2>
        </div>

        <div class="table-responsive">
            <table id="data-table-basic" class="table table-striped">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Tipo</th>
                    <th>Proveedor</th>
                    <th>Marca</th>
                    <th>Descripcion</th>
                </tr>
                </thead>
                <tbody>
                {% for elemento in productos %}
                    <tr>
                        <td>{{ elemento.id }}</td>
                        <td>{{ elemento.tipo }}</td>
                        <td>{{ elemento.proveedor }} </td>
                        <td>{{ elemento.marca }}</td>
                        <td>{{ elemento.descripcion }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    <a href="{% url 'ajustes:nuevo_producto' %}"
       class="btn btn-float btn-success m-btn waves-effect waves-circle waves-float">
        <i class="zmdi zmdi-plus"></i>
    </a>

    {% if is_paginated %}
        {% include 'Main/paginator.html' %}
    {% endif %}

{% endblock %}