Apps/Ajustes/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import inicio, ElementosView, nuevo_elemento, nuevo_producto, ProductoView
from .views import origen

urlpatterns = [
    url(r'^inicio/', inicio, name='inicio'),
    url(r'^elementos/', login_required(ElementosView.as_view()), name='elementos'),
    url(r'^nuevo-elemento', nuevo_elemento, name='nuevo_elemento'),
    url(r'^nuevo-producto', nuevo_producto, name='nuevo_producto'),
    url(r'^productos', ProductoView.as_view(), name='productos'),
    url(r'^origen/(?P<id>\w+)', origen, name='p_p')
]

Apps/Empleados/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from views import IncidenteUsuarioView, crear_incidente_usuario, crear_usuario, usuarios
from views import notificaciones, ver_solucion, incidentes_solucionados, incidentes_usuario
from views import incidentes_no_solucionados

urlpatterns = [
    url(r'^incidentes', login_required(IncidenteUsuarioView.as_view()), name='incidentes'),
    url(r'^registrar-incidente', crear_incidente_usuario, name='crear_incidente'),
    url(r'^registrar-usuario', crear_usuario, name='crear_usuario'),
    url(r'^usuarios', usuarios, name='usuarios'),
    url(r'^notificaciones', notificaciones, name='notificaciones'),
    url(r'^solucion/(?P<id>\w+)', ver_solucion, name='ver_solucion'),
    url(r'^incidentes-solucionados', incidentes_solucionados, name='ver_incidentes_solucionados'),
    url(r'^incidentes-no-solucionados', incidentes_no_solucionados, name='ver_incidentes_no_solucionados'),
    url(r'^incidentes-usuario', incidentes_usuario, name='incidentes_usuario'),
]

Apps/Soporte/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import IncidenteView, crear_incidente, crear_incidente_elemento
from .views import crear_solucion, incidente_elemento, solucion_incidente, solucionar_incidente
from .views import ProveedorView, crear_proveedor, crear_marca, MarcaView, editar_marca
from .views import proveedor_marca

urlpatterns = [
    url(r'^incidentes/', login_required(IncidenteView.as_view()), name='incidentes'),
    url(r'^crear-incidente', crear_incidente, name='crear_incidente'),
    url(r'^crear-solucion/(?P<id>\w+)/', crear_solucion, name='crear_solucion'),
    url(r'^incidente/(?P<id_objeto>\w+)/', incidente_elemento, name='incidentes_objeto'),
    url(r'^solucion-incidente/(?P<id_incidente>\w+)/', solucion_incidente, name='solucion_incidente'),
    url(r'^solucionar-incidente/(?P<id_incidente>\w+)/', solucionar_incidente, name='solucionar_incidente'),
    url(r'^incidente-elemento/(?P<id_elemento>\w+)/', crear_incidente_elemento, name='incidente_elemento'),
    url(r'^proveedores/', ProveedorView.as_view(), name='proveedores'),
    url(r'^crear-proveedor', crear_proveedor, name='crear_proveedor'),
    url(r'^crear-marca', crear_marca, name='crear_marca'),
    url(r'^marcas', MarcaView.as_view(), name='marcas'),
    url(r'editar-marca/(?P<id>\w+)/', editar_marca, name='editar_marca'),
    url(r'^asignar-proveedor-marca', proveedor_marca, name='proveedor_marca'),

]

itil/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import logout
from django.shortcuts import redirect
from Apps.Ajustes.views import login


def salir(request):
    logout(request)
    return redirect('log_in')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    #   url de login
    url(r'^$', login, name='log_in'),
    url(r'^login/', login, name='log_in_'),
    url(r'^salir', salir, name='salir'),
    # urls de ajustes
    url(r'^ajustes/', include('Apps.Ajustes.urls', namespace='ajustes')),
    # urls de soporte
    url(r'^soporte/', include('Apps.Soporte.urls', namespace='soporte')),

    url(r'^empleados/', include('Apps.Empleados.urls', namespace='empleado')),

]

Apps/Empleados/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models

# Create your models here.
from Apps.Ajustes.models import Empleado
from Apps.Soporte.models import Incidente, Solucion


class NotificacionSolucion(models.Model):

    empleado = models.ForeignKey(Empleado)
    incidente = models.ForeignKey(Incidente)
    solucion = models.ForeignKey(Solucion)
    encargado = models.ForeignKey(User, related_name='encargado', editable=False)
    hora = models.TimeField(auto_now_add=True)
    fecha = models.DateField(auto_now_add=True)
    visto = models.BooleanField(default=False)

Apps/Empleados/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from Apps.Ajustes.forms import BaseForm
from Apps.Ajustes.models import ElementoConfiguracion, Empleado
from Apps.Soporte.models import Incidente


class IncidenteUsuarioForm(BaseForm):

    form_title = 'Incidente'
    time_widget = forms.widgets.TimeInput(attrs={'class': 'time-pick'})
    valid_time_formats = ['%H:%M', '%I:%M%p', '%I:%M %p']
    hora = forms.TimeField(widget=time_widget, help_text='ex: 10:30AM', input_formats=valid_time_formats)
    elemento_afectado = forms.ModelChoiceField(
        queryset=ElementoConfiguracion.objects.all(), empty_label=None)

    class Meta:
        model = Incidente
        fields = ('elemento_afectado',
                  'categoria',
                  'prioridad',
                  'asunto',
                  'descripcion',
                  'hora',
                  'fecha'
                  )
        exclude = ('cerrado', 'soluciones')


class EmpleadoForm(UserCreationForm):

    form_title = 'Incidente'

    first_name = forms.CharField(required=True, label='Nombres')
    last_name = forms.CharField(required=True, label='Apellidos')
    email = forms.EmailField(required=True, label='Correo Electronico')

    class Meta:
        model = Empleado
        fields = ('username',
                  'first_name',
                  'last_name',
                  'departamento',
                  'cargo',
                  'email')

Apps/Empleados/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from Apps.Ajustes.models import ElementoConfiguracion, Empleado
from Apps.Ajustes.views import ListBase
from Apps.Empleados.forms import IncidenteUsuarioForm, EmpleadoForm
from Apps.Empleados.models import NotificacionSolucion
from Apps.Soporte.models import Incidente, Solucion


class IncidenteUsuarioView(ListBase):
    template_name = 'listados/soporte/incidentes.html'
    paginate_by = 10
    queryset = Incidente.objects.all()
    model = Incidente

    def get_context_data(self, **kwargs):
        context = super(IncidenteUsuarioView, self).get_context_data(**kwargs)
        context['incidentes_lista'] = True
        context['incidentes'] = Incidente.objects.filter(usuario=self.request.user)
        return context


@login_required
def crear_incidente_usuario(request):
    form = IncidenteUsuarioForm()
    elemento_afectado = ElementoConfiguracion.objects.filter(usuario=request.user)
    form.fields['elemento_afectado'].queryset = elemento_afectado
    if request.POST:
        form = IncidenteUsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('empleado:incidentes')
    context = {
        'form': form,
        'accion': 'Crear',
    }
    return render(request, 'Main/forms/baseForm.html', context)


@login_required
def crear_usuario(request):
    form = EmpleadoForm()
    if request.POST:
        form = EmpleadoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('empleado:usuarios')
    context = {
        'form': form,
        'accion': 'Crear',
    }
    return render(request, 'Main/forms/baseForm.html', context)


@login_required
def usuarios(request):
    usuarios = Empleado.objects.order_by('-id')
    return render(request, 'listados/empleados/empleados.html', {
        'usuarios': usuarios
    })


@login_required
def notificaciones(request):
    alertas = None
    if hasattr(request.user, 'empleado'):
        user = Empleado.objects.get(id=request.user.id)
        alertas = NotificacionSolucion.objects.filter(
            empleado=user
        )
        print(alertas)
    return render(request, 'listados/empleados/notificaciones.html', {
        'notificaciones': alertas
    })


@login_required
def ver_solucion(request, **kwargs):
    id = kwargs.get('id')
    solucion_notificacion = NotificacionSolucion.objects.get(solucion_id=id)
    if hasattr(request.user, 'empleado') and solucion_notificacion.visto is False:
        solucion_notificacion.visto = True
        solucion_notificacion.save()
        user = Empleado.objects.get(id=request.user.id)
        user.notificaciones -= 1
        user.save()
    solucion = Solucion.objects.filter(id=id)
    context = {
        'soluciones': solucion,
        'incidente': solucion_notificacion.incidente
    }
    return render(request, 'listados/soporte/soluciones.html', context)


@login_required
def incidentes_usuario(request):
    objetos = Incidente.objects.filter(
        usuario=request.user.empleado
    )
    lista = True if objetos.count() > 0 else False
    return render(request, 'listados/soporte/incidentes.html', {
        'incidentes': objetos,
        'incidentes_lista': lista

    })


@login_required
def incidentes_solucionados(request):
    incidentes = Incidente.objects.filter(
        usuario=request.user,
        cerrado=True
    )
    return render(request, 'listados/soporte/incidentes.html', {
        'incidentes': incidentes
    })


@login_required
def incidentes_no_solucionados(request):
    incidentes = Incidente.objects.filter(
        usuario=request.user,
        cerrado=False
    )
    return render(request, 'listados/soporte/incidentes.html', {
        'incidentes': incidentes
    })

templates/Main/menu/administrador.html
<li class="sub-menu">
    <a>
        <i class="zmdi zmdi-nature-people zmdi-hc-fw"></i>
        Empleados
    </a>

    <ul>
        <li>
            <a href="{% url 'empleado:crear_usuario' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Crear Empleado
            </a>
        </li>
        <li>
            <a href="{% url 'empleado:usuarios' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Lista de empleados

            </a>
        </li>
    </ul>
</li>


<li class="sub-menu">
    <a>
        <i class="zmdi  zmdi-satellite zmdi-hc-fw"></i>
        Marcas Proveedores
    </a>

    <ul>
        <li>
            <a href="{% url 'soporte:crear_proveedor' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Crear proveedor
            </a>
        </li>
        <li>
            <a href="{% url 'soporte:proveedores' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Lista de proveedores
            </a>
        </li>
        <li>
            <a href="{% url 'soporte:crear_marca' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Crear Marca
            </a>
        </li>
        <li>
            <a href="{% url 'soporte:marcas' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Lista de Marcas
            </a>
        </li>
        <li>
            <a href="{% url 'soporte:proveedor_marca' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> proveedor marca
            </a>
        </li>
    </ul>
</li>

<li class="sub-menu">
    <a>
        <i class="zmdi  zmdi-puzzle-piece zmdi-hc-fw"></i>
        Productos
    </a>

    <ul>
        <li>
            <a href="{% url 'ajustes:productos' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Lista de productos
            </a>
        </li>
        <li>
            <a href="{% url 'ajustes:nuevo_producto' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Crear Producto
            </a>
        </li>
    </ul>
</li>


<li class="sub-menu">
    <a>
        <i class="zmdi  zmdi-dns zmdi-hc-fw"></i>
        Ayuda Y Soporte
    </a>

    <ul>
        <li>
            <a href="{% url 'ajustes:elementos' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Elementos de Configuracion
            </a>
        </li>
        <li>
            <a href="{% url 'soporte:incidentes' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Incidentes
            </a>
        </li>
    </ul>
</li>

templates/Main/menu/empleado.html
<li>
    <a href="{% url 'empleado:incidentes' %}">
        <i class="zmdi  zmdi-home zmdi-hc-fw"></i>
        Inicio
    </a>
</li>

<li>
    <a href="{% url 'empleado:crear_incidente' %}">
        <i class="zmdi  zmdi-dns zmdi-hc-fw"></i>
        Registrar Incidente
    </a>
</li>

<li class="sub-menu">
    <a>
        <i class="zmdi  zmdi-dns zmdi-hc-fw"></i>
        Historico
    </a>
    <ul>
        <li>
            <a href="{% url 'empleado:incidentes_usuario' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Todos los incidentes
            </a>
        </li>
        <li>
            <a href="{% url 'empleado:ver_incidentes_solucionados' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Incidentes Solucionados
            </a>
        </li>
        <li>
            <a href="{% url 'empleado:ver_incidentes_no_solucionados' %}">
                <i class="zmdi zmdi-globe-lock zmdi-hc-fw"></i> Incidentes Sin Solucionar
            </a>
        </li>
    </ul>
</li>