Apps/Empleados/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from views import IncidenteUsuarioView, crear_incidente_usuario, crear_usuario, usuarios
from views import notificaciones, ver_solucion, incidentes_solucionados, incidentes_usuario
from views import incidentes_no_solucionados

urlpatterns = [
    url(r'^incidentes', login_required(IncidenteUsuarioView.as_view()), name='incidentes'),
    url(r'^registrar-incidente', crear_incidente_usuario, name='crear_incidente'),
    url(r'^registrar-usuario', crear_usuario, name='crear_usuario'),
    url(r'^usuarios', usuarios, name='usuarios'),
    url(r'^notificaciones', notificaciones, name='notificaciones'),
    url(r'^solucion/(?P<id>\w+)', ver_solucion, name='ver_solucion'),
    url(r'^incidentes-solucionados', incidentes_solucionados, name='ver_incidentes_solucionados'),
    url(r'^incidentes-no-solucionados', incidentes_no_solucionados, name='ver_incidentes_no_solucionados'),
    url(r'^incidentes-usuario', incidentes_usuario, name='incidentes_usuario'),
]

itil/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import logout
from django.shortcuts import redirect
from Apps.Ajustes.views import login


def salir(request):
    logout(request)
    return redirect('log_in')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    #   url de login
    url(r'^$', login, name='log_in'),
    url(r'^login/', login, name='log_in_'),
    url(r'^salir', salir, name='salir'),
    # urls de ajustes
    url(r'^ajustes/', include('Apps.Ajustes.urls', namespace='ajustes')),
    # urls de soporte
    url(r'^soporte/', include('Apps.Soporte.urls', namespace='soporte')),

    url(r'^empleados/', include('Apps.Empleados.urls', namespace='empleado')),

]

Apps/Empleados/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models

# Create your models here.
from Apps.Ajustes.models import Empleado
from Apps.Soporte.models import Incidente, Solucion


class NotificacionSolucion(models.Model):

    empleado = models.ForeignKey(Empleado)
    incidente = models.ForeignKey(Incidente)
    solucion = models.ForeignKey(Solucion)
    encargado = models.ForeignKey(User, related_name='encargado', editable=False)
    hora = models.TimeField(auto_now_add=True)
    fecha = models.DateField(auto_now_add=True)
    visto = models.BooleanField(default=False)

Apps/Empleados/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from Apps.Ajustes.forms import BaseForm
from Apps.Ajustes.models import ElementoConfiguracion, Empleado
from Apps.Soporte.models import Incidente


class IncidenteUsuarioForm(BaseForm):

    form_title = 'Incidente'
    time_widget = forms.widgets.TimeInput(attrs={'class': 'time-pick'})
    valid_time_formats = ['%H:%M', '%I:%M%p', '%I:%M %p']
    hora = forms.TimeField(widget=time_widget, help_text='ex: 10:30AM', input_formats=valid_time_formats)
    elemento_afectado = forms.ModelChoiceField(
        queryset=ElementoConfiguracion.objects.all(), empty_label=None)

    class Meta:
        model = Incidente
        fields = ('elemento_afectado',
                  'categoria',
                  'prioridad',
                  'asunto',
                  'descripcion',
                  'hora',
                  'fecha'
                  )
        exclude = ('cerrado', 'soluciones')


class EmpleadoForm(UserCreationForm):

    form_title = 'Incidente'

    first_name = forms.CharField(required=True, label='Nombres')
    last_name = forms.CharField(required=True, label='Apellidos')
    email = forms.EmailField(required=True, label='Correo Electronico')

    class Meta:
        model = Empleado
        fields = ('username',
                  'first_name',
                  'last_name',
                  'departamento',
                  'cargo',
                  'email')

Apps/Empleados/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from Apps.Ajustes.models import ElementoConfiguracion, Empleado
from Apps.Ajustes.views import ListBase
from Apps.Empleados.forms import IncidenteUsuarioForm, EmpleadoForm
from Apps.Empleados.models import NotificacionSolucion
from Apps.Soporte.models import Incidente, Solucion


class IncidenteUsuarioView(ListBase):
    template_name = 'listados/soporte/incidentes.html'
    paginate_by = 10
    queryset = Incidente.objects.all()
    model = Incidente

    def get_context_data(self, **kwargs):
        context = super(IncidenteUsuarioView, self).get_context_data(**kwargs)
        context['incidentes_lista'] = True
        context['incidentes'] = Incidente.objects.filter(usuario=self.request.user)
        return context


@login_required
def crear_incidente_usuario(request):
    form = IncidenteUsuarioForm()
    elemento_afectado = ElementoConfiguracion.objects.filter(usuario=request.user)
    form.fields['elemento_afectado'].queryset = elemento_afectado
    if request.POST:
        form = IncidenteUsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('empleado:incidentes')
    context = {
        'form': form,
        'accion': 'Crear',
    }
    return render(request, 'Main/forms/baseForm.html', context)


@login_required
def crear_usuario(request):
    form = EmpleadoForm()
    if request.POST:
        form = EmpleadoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('empleado:usuarios')
    context = {
        'form': form,
        'accion': 'Crear',
    }
    return render(request, 'Main/forms/baseForm.html', context)


@login_required
def usuarios(request):
    usuarios = Empleado.objects.order_by('-id')
    return render(request, 'listados/empleados/empleados.html', {
        'usuarios': usuarios
    })


@login_required
def notificaciones(request):
    alertas = None
    if hasattr(request.user, 'empleado'):
        user = Empleado.objects.get(id=request.user.id)
        alertas = NotificacionSolucion.objects.filter(
            empleado=user
        )
        print(alertas)
    return render(request, 'listados/empleados/notificaciones.html', {
        'notificaciones': alertas
    })


@login_required
def ver_solucion(request, **kwargs):
    id = kwargs.get('id')
    solucion_notificacion = NotificacionSolucion.objects.get(solucion_id=id)
    if hasattr(request.user, 'empleado') and solucion_notificacion.visto is False:
        solucion_notificacion.visto = True
        solucion_notificacion.save()
        user = Empleado.objects.get(id=request.user.id)
        user.notificaciones -= 1
        user.save()
    solucion = Solucion.objects.filter(id=id)
    context = {
        'soluciones': solucion,
        'incidente': solucion_notificacion.incidente
    }
    return render(request, 'listados/soporte/soluciones.html', context)


@login_required
def incidentes_usuario(request):
    objetos = Incidente.objects.filter(
        usuario=request.user.empleado
    )
    lista = True if objetos.count() > 0 else False
    return render(request, 'listados/soporte/incidentes.html', {
        'incidentes': objetos,
        'incidentes_lista': lista

    })


@login_required
def incidentes_solucionados(request):
    incidentes = Incidente.objects.filter(
        usuario=request.user,
        cerrado=True
    )
    return render(request, 'listados/soporte/incidentes.html', {
        'incidentes': incidentes
    })


@login_required
def incidentes_no_solucionados(request):
    incidentes = Incidente.objects.filter(
        usuario=request.user,
        cerrado=False
    )
    return render(request, 'listados/soporte/incidentes.html', {
        'incidentes': incidentes
    })

templates/listados/empleados/empleados.html
{% extends 'Main/base.html' %}

{% block contenido %}

    <div class="card">
        <div class="card-header">
            <h2>
                Lista de Empleados
            </h2>
        </div>

        <div class="table-responsive">
            <table id="data-table-basic" class="table table-striped">
                <thead>
                <tr>
                    <th class="text-center">
                        id
                    </th>
                    <th class="text-center">
                        usuario
                    </th>
                    <th class="text-center">
                        nombre y apellidos
                    </th>
                    <th class="text-center">
                        departamento
                    </th>
                    <th class="text-center">
                        cargo
                    </th>
                    <th class="text-center">
                        Correo
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for elemento in usuarios %}
                    <tr>
                        <td class="text-center">{{ elemento.id }}</td>
                        <td class="text-center">{{ elemento.username }}</td>
                        <td class="text-center">{{ elemento.first_name }} {{ elemento.last_name }}</td>
                        <td class="text-center">{{ elemento.departamento }}</td>
                        <th class="text-center">{{ elemento.cargo }}</th>
                        <th class="text-center">{{ elemento.email }}</th>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    <a href="{% url 'empleado:crear_usuario' %}"
       class="btn btn-float btn-success m-btn waves-effect waves-circle waves-float">
        <i class="zmdi zmdi-plus"></i>
    </a>

    {% if is_paginated %}
        {% include 'Main/paginator.html' %}
    {% endif %}

{% endblock %}

templates/listados/empleados/notificaciones.html
{% extends 'Main/base.html' %}

{% block contenido %}

    <div class="card">
        <div class="card-header">
            <h2 class="text-center">
                {% if notificaciones.count > 0 %}
                    Echale un vistazo a tus notificaciones
                    usted tiene {{ notificaciones.count }} notificaciones sin revisar
                {% else %}
                    usted no tiene notificaciones pendientes
                {% endif %}
            </h2>
        </div>

        <div class="table-responsive">
            <table id="data-table-basic" class="table table-striped">
                <thead>
                <tr>
                    <th class="text-center">
                        incidente
                    </th>
                    <th class="text-center">
                        solucion
                    </th>
                    <th class="text-center">Hora</th>
                    <th class="text-center">Fecha</th>
                    <th class="text-center">
                        visto
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for elemento in notificaciones %}
                    <tr>
                        <td class="text-center">{{ elemento.incidente.id }}</td>
                        <td class="text-center">
                            <a href="{% url 'empleado:ver_solucion' elemento.solucion.id %}">{{ elemento.solucion }}</a>
                        </td>
                        <td class="text-center">{{ elemento.hora }}</td>
                        <td class="text-center">{{ elemento.fecha }}</td>
                        <td class="text-center">
                            <strong>
                                {% if elemento.visto %}
                                    <button class="btn bgm-green btn-xs">
                                        <i class="zmdi zmdi-check"></i>
                                    </button>
                                {% else %}
                                    <button class="btn bgm-red btn-xs">
                                        <i class="zmdi zmdi-close"></i>
                                    </button>
                                {% endif %}
                            </strong>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    {% if is_paginated %}
        {% include 'Main/paginator.html' %}
    {% endif %}

{% endblock %}