Apps/Ajustes/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import inicio, ElementosView, nuevo_elemento, nuevo_producto, ProductoView
from .views import origen

urlpatterns = [
    url(r'^inicio/', inicio, name='inicio'),
    url(r'^elementos/', login_required(ElementosView.as_view()), name='elementos'),
    url(r'^nuevo-elemento', nuevo_elemento, name='nuevo_elemento'),
    url(r'^nuevo-producto', nuevo_producto, name='nuevo_producto'),
    url(r'^productos', ProductoView.as_view(), name='productos'),
    url(r'^origen/(?P<id>\w+)', origen, name='p_p')
]

Apps/Soporte/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import IncidenteView, crear_incidente, crear_incidente_elemento
from .views import crear_solucion, incidente_elemento, solucion_incidente, solucionar_incidente
from .views import ProveedorView, crear_proveedor, crear_marca, MarcaView, editar_marca
from .views import proveedor_marca

urlpatterns = [
    url(r'^incidentes/', login_required(IncidenteView.as_view()), name='incidentes'),
    url(r'^crear-incidente', crear_incidente, name='crear_incidente'),
    url(r'^crear-solucion/(?P<id>\w+)/', crear_solucion, name='crear_solucion'),
    url(r'^incidente/(?P<id_objeto>\w+)/', incidente_elemento, name='incidentes_objeto'),
    url(r'^solucion-incidente/(?P<id_incidente>\w+)/', solucion_incidente, name='solucion_incidente'),
    url(r'^solucionar-incidente/(?P<id_incidente>\w+)/', solucionar_incidente, name='solucionar_incidente'),
    url(r'^incidente-elemento/(?P<id_elemento>\w+)/', crear_incidente_elemento, name='incidente_elemento'),
    url(r'^proveedores/', ProveedorView.as_view(), name='proveedores'),
    url(r'^crear-proveedor', crear_proveedor, name='crear_proveedor'),
    url(r'^crear-marca', crear_marca, name='crear_marca'),
    url(r'^marcas', MarcaView.as_view(), name='marcas'),
    url(r'editar-marca/(?P<id>\w+)/', editar_marca, name='editar_marca'),
    url(r'^asignar-proveedor-marca', proveedor_marca, name='proveedor_marca'),

]

itil/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import logout
from django.shortcuts import redirect
from Apps.Ajustes.views import login


def salir(request):
    logout(request)
    return redirect('log_in')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    #   url de login
    url(r'^$', login, name='log_in'),
    url(r'^login/', login, name='log_in_'),
    url(r'^salir', salir, name='salir'),
    # urls de ajustes
    url(r'^ajustes/', include('Apps.Ajustes.urls', namespace='ajustes')),
    # urls de soporte
    url(r'^soporte/', include('Apps.Soporte.urls', namespace='soporte')),

    url(r'^empleados/', include('Apps.Empleados.urls', namespace='empleado')),

]

Apps/Soporte/models.py
from __future__ import unicode_literals

from django.db import models
from smart_selects.db_fields import ChainedForeignKey
from Apps.Ajustes.models import ElementoConfiguracion, MainModel, Empleado


# Create your models here.


class Prioridad(MainModel):

    horas_de_resolucion = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Prioridad'
        verbose_name_plural = 'Prioridades'

    def __unicode__(self):
        data = '{0}, {1} horas'.format(self.nombre, self.horas_de_resolucion)
        return data


class CategoriaIncidente(MainModel):

    class Meta:
        verbose_name_plural = 'Cateogrias de incidentes'
        verbose_name = 'Categoria de incidente'


class Incidente(models.Model):

    usuario = models.ForeignKey(Empleado, editable=False)
    elemento_afectado = models.ForeignKey(ElementoConfiguracion)
    categoria = models.ForeignKey(CategoriaIncidente)
    asunto = models.CharField(max_length=50)
    descripcion = models.TextField()
    cerrado = models.BooleanField(default=False)
    prioridad = models.ForeignKey(Prioridad)
    hora = models.TimeField()
    fecha = models.DateField()
    soluciones = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Incidente'
        verbose_name_plural = 'Incidentes'

    def __unicode__(self):
        return "incidente #{0}".format(self.id)

    def save(self, *args, **kwargs):
        if not self.id:
            self.usuario = self.elemento_afectado.usuario
            self.elemento_afectado.incidentes += 1
            self.elemento_afectado.save()
        super(Incidente, self).save(*args, **kwargs)


class Solucion(models.Model):

    incidente = models.ForeignKey(Incidente)
    elemento_afectado = models.ForeignKey(ElementoConfiguracion)
    descripcion = models.TextField()

    class Meta:
        verbose_name = 'Solucion'
        verbose_name_plural = 'Soluciones'

    def save(self, *args, **kwargs):
        if not self.id:
            self.incidente.soluciones += 1
            self.incidente.save()
        super(Solucion, self).save(*args, **kwargs)

    def __unicode__(self):
        return "solucion al problema incidente #{0}".format(self.incidente.id)

Apps/Soporte/forms.py
from django import forms
from Apps.Ajustes.forms import BaseForm
from Apps.Ajustes.models import ElementoConfiguracion, Proveedor, Marca, ProveedorMarca
from Apps.Soporte.models import Incidente, Solucion


class IncidenteForm(BaseForm):

    form_title = 'Incidente'
    time_widget = forms.widgets.TimeInput(attrs={'class': 'time-pick'})
    valid_time_formats = ['%H:%M', '%I:%M%p', '%I:%M %p']
    hora = forms.TimeField(widget=time_widget, help_text='ex: 10:30AM', input_formats=valid_time_formats)
    elemento_afectado = forms.ModelChoiceField(
        queryset=ElementoConfiguracion.objects.all(), empty_label=None)

    class Meta:
        model = Incidente
        fields = ('__all__')
        exclude = ('cerrado', 'soluciones')


class SolucionForm(BaseForm):

    form_title = 'Solucion'
    incidente = forms.ModelChoiceField(
        queryset=Incidente.objects.all(), empty_label=None)
    elemento_afectado = forms.ModelChoiceField(
        queryset=ElementoConfiguracion.objects.all(), empty_label=None)

    class Meta:
        model = Solucion
        fields = ('incidente', 'elemento_afectado', 'descripcion')


class ProveedorForm(BaseForm):

    form_title = 'Proveedor'

    class Meta:
        model = Proveedor
        fields = ('__all__')


class MarcaForm(BaseForm):

    form_title = 'Marca'

    class Meta:
        model = Marca
        fields = ('__all__')


class ProveedorMarcaForm(BaseForm):

    form_title = 'Proveedor de marca'

    class Meta:
        model = ProveedorMarca
        fields = ('__all__')

Apps/Soporte/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from Apps.Ajustes.models import ElementoConfiguracion, Proveedor, Marca, ProveedorMarca
from Apps.Ajustes.views import ListBase
from Apps.Empleados.models import NotificacionSolucion
from Apps.Soporte.forms import IncidenteForm, SolucionForm, ProveedorForm, MarcaForm, ProveedorMarcaForm
from Apps.Soporte.models import Incidente, Solucion

"""
    elemento = ElementoConfiguracion.objects.get(id=id)
    queryset = Incidente.objects.filter(elemento_afectado=elemento)
"""


class IncidenteView(ListBase):
    template_name = 'listados/soporte/incidentes.html'
    model = Incidente
    paginate_by = 10
    context_object_name = 'incidentes'
    queryset = Incidente.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(IncidenteView, self).get_context_data(**kwargs)
        context['incidentes_lista'] = True
        return context


@login_required
def crear_incidente(request):
    form = IncidenteForm()
    if request.POST:
        form = IncidenteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('soporte:incidentes')
    context = {
        'form': form,
        'accion': 'Crear',
    }
    return render(request, 'Main/forms/baseForm.html', context)


@login_required
def crear_incidente_elemento(request, **kwargs):
    id = kwargs.get('id_elemento')
    form = IncidenteForm()
    elemento_afectado = ElementoConfiguracion.objects.filter(id=id)
    form.fields['elemento_afectado'].queryset = elemento_afectado
    if request.POST:
        form = IncidenteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('soporte:incidentes_objeto', id)
    context = {
        'form': form,
        'accion': 'Crear'
    }
    return render(request, 'Main/forms/baseForm.html', context)


@login_required
def crear_solucion(request, **incidente):
    id = incidente.get('id')
    form = SolucionForm()

    incidente_top = Incidente.objects.get(id=id)
    usuario = incidente_top.elemento_afectado.usuario
    incidente = Incidente.objects.filter(id=id)
    form.fields['incidente'].queryset = incidente

    elemento_afectado = ElementoConfiguracion.objects.filter(id=incidente_top.elemento_afectado.id)
    form.fields['elemento_afectado'].queryset = elemento_afectado

    if request.POST:
        form = SolucionForm(request.POST)
        if form.is_valid():
            form.save()
            solucion = Solucion.objects.filter(incidente=incidente_top).order_by('-id')[0]
            NotificacionSolucion(
                incidente=incidente_top,
                solucion=solucion,
                empleado=usuario.empleado,
                encargado=request.user
            ).save()
            empleado = usuario
            empleado.notificaciones += 1
            empleado.save()
            return redirect('soporte:solucion_incidente', id)
    context = {
        'form': form,
        'accion': 'Crear'
    }
    return render(request, 'Main/forms/baseForm.html', context)


@login_required
def incidente_elemento(request, **kwargs):
    id = kwargs.get('id_objeto')
    elemento = ElementoConfiguracion.objects.get(id=id)
    incidentes = Incidente.objects.filter(elemento_afectado=elemento)
    context = {
        'incidentes': incidentes,
        'elemento': elemento
    }
    return render(request, 'listados/soporte/incidentes.html', context)


@login_required
def solucion_incidente(request, **kwargs):
    id = kwargs.get('id_incidente')
    incidente = Incidente.objects.get(id=id)
    soluciones = Solucion.objects.filter(incidente=incidente)
    context = {
        'soluciones': soluciones,
        'incidente': incidente
    }
    return render(request, 'listados/soporte/soluciones.html', context)


@login_required
def solucionar_incidente(request, **kwargs):
    id = kwargs.get('id_incidente')
    incidente = Incidente.objects.get(id=id)
    if incidente.soluciones > 0:
        incidente.cerrado = True
        incidente.save()
        return redirect('soporte:incidentes')
    else:
        return render(request, 'listados/soporte/cerrar_incidente_fail.html')


@login_required
def crear_proveedor(request):
    form = ProveedorForm()
    if request.POST:
        form = ProveedorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('soporte:proveedores')
    context = {
        'form': form,
        'accion': 'Crear',
    }
    return render(request, 'Main/forms/baseForm.html', context)


class ProveedorView(ListBase):
    template_name = 'listados/soporte/proveedores.html'
    model = Proveedor
    paginate_by = 10
    context_object_name = 'proveedores'
    queryset = Proveedor.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(ProveedorView, self).get_context_data(**kwargs)
        return context


@login_required
def crear_marca(request):
    form = MarcaForm()
    if request.POST:
        form = MarcaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('soporte:marcas')
    context = {
        'form': form,
        'accion': 'Crear',
    }
    return render(request, 'Main/forms/baseForm.html', context)


class MarcaView(ListBase):
    template_name = 'listados/soporte/marcas.html'
    model = Marca
    paginate_by = 10
    context_object_name = 'proveedores'
    queryset = Marca.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(MarcaView, self).get_context_data(**kwargs)
        return context


@login_required
def editar_marca(request, **kwargs):
    id = kwargs.get('id')
    marca = Marca.objects.get(id=id)
    form = MarcaForm(instance=marca)
    if request.POST:
        form = MarcaForm(request.POST, instance=marca)
        if form.is_valid():
            form.save()
            return redirect('soporte:marcas')
    context = {
        'form': form,
        'accion': 'Crear',
    }
    return render(request, 'Main/forms/baseForm.html', context)


@login_required
def proveedor_marca(request):
    form = ProveedorMarcaForm()
    if request.POST:
        form = ProveedorMarcaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('soporte:marcas')
    context = {
        'form': form,
        'accion': 'Asignar',
    }
    return render(request, 'Main/forms/baseForm.html', context)

templates/listados/soporte/incidentes.html
{% extends 'Main/base.html' %}

{% block contenido %}

    {% if incidentes %}
        <div class="card">
            <div class="card-header">
                <h2>
                    Lista de Incidentes
                    {% if elemento %}
                        del elemento de configuracion :
                        <br>
                        <strong style="color: blue">
                            {{ elemento }}
                        </strong>
                    {% endif %}
                </h2>
            </div>

            <div class="table-responsive">
                <table id="data-table-basic" class="table table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">Ticket</th>
                        <th class="text-center">Prioridad</th>
                        <th class="text-center">Solucionado</th>
                        <th class="text-center">Elemento Afectado</th>
                        <th class="text-center">Categoria</th>
                        <th class="text-center">Hora</th>
                        <th class="text-center">Fecha</th>
                        <th class="text-center">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for incidente in incidentes %}
                        <tr>
                            <td id="ticket_{{ incidente.id }}" class="text-center">
                                #{{ incidente.id }}
                            </td>
                            <td id="prioridad_{{ incidente.id }}" class="text-center">
                                {{ incidente.prioridad }}
                            </td>
                            <td id="cerrado_{{ incidente.id }}" class="text-center">
                                <strong>
                                    {% if incidente.cerrado %}
                                        <button class="btn bgm-green btn-xs">
                                            <i class="zmdi zmdi-check"></i>
                                        </button>
                                    {% else %}
                                        <button class="btn bgm-red btn-xs">
                                            <i class="zmdi zmdi-close"></i>
                                        </button>
                                    {% endif %}
                                </strong>
                            </td>
                            <td id="elemento_{{ incidente.id }}" class="text-center">
                                {{ incidente.elemento_afectado.producto.descripcion }}
                            </td>
                            <td id="categoria_{{ incidente.id }}" class="text-center">
                                {{ incidente.categoria }}
                            </td>
                            <td id="hora_{{ incidente.id }}" class="text-center">
                                {{ incidente.hora }}
                            </td>
                            <td id="fecha_{{ incidente.id }}" class="text-center">
                                {{ incidente.fecha }}
                            </td>
                            <td id="asunto_{{ incidente.id }}" class="hidden">
                                {{ incidente.asunto }}
                            </td>
                            <td id="descripcion_{{ incidente.id }}" class="hidden">
                                {{ incidente.descripcion }}
                            </td>
                            <td id="usuario_{{ incidente.id }}" class="hidden">
                                {{ incidente.elemento_afectado.usuario }}
                            </td>
                            <td id="serial_{{ incidente.id }}" class="hidden">
                                {{ incidente.elemento_afectado.serial }}
                            </td>
                            <td>
                                <a href="{% url 'soporte:solucion_incidente' incidente.id %}"
                                   class="btn bgm-purple btn-xs"
                                   data-toggle="tooltip" data-placement="top" title="Ver Soluciones">
                                    <i class="zmdi zmdi-eye"></i>
                                </a>
                                <a href="#myModal" data-toggle="modal" onshow="tooltip"
                                   onclick="GetDataModal({{ incidente.id }})"
                                   class="btn bgm-orange text-center btn-xs">
                                    <i class="zmdi zmdi-mail-send"></i>
                                </a>
                                {% if not incidente.cerrado and request.user.is_superuser %}
                                    <a href="{% url 'soporte:solucionar_incidente' incidente.id %}"
                                       class="btn bgm-green btn-xs"
                                       data-toggle="tooltip" data-placement="top" title="Solucionar">
                                        <i class="zmdi zmdi-check"></i>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>

        <a href="{% url 'soporte:crear_incidente' %}"
           class="btn btn-float btn-success m-btn waves-effect waves-circle waves-float">
            <i class="zmdi zmdi-plus"></i>
        </a>

        {% if is_paginated %}
            {% include 'Main/paginator.html' %}
        {% endif %}

        <script>
            var url_id = '';
            function GetDataModal(id) {
                url_id = id;
                var prioridad = $('#prioridad_' + id).text();
                var cerrado = $('#cerrado_' + id).text();
                var elemento = $('#elemento_' + id).text();
                var categoria = $('#categoria_' + id).text();
                var hora = $('#hora_' + id).text();
                var fecha = $('#fecha_' + id).text();
                var asunto = $('#asunto_' + id).text();
                var descripcion = $('#descripcion_' + id).text();
                var usuario = $('#usuario_' + id).text();
                var serial = $('#serial_' + id).text()

                $("#elemento").text(elemento);
                $("#fecha").text(fecha);
                $("#hora").text(hora);
                $("#categoria").text(categoria);
                $("#asunto").text(asunto);
                $("#descripcion").text(descripcion);
                $('#usuario').text(usuario);
                $('#serial').text(serial)
            }

            function SolucionarProblema() {
                host = window.location.hostname
                route = "http://" + host + "/soporte/crear-solucion/" + url_id + "/";
                window.location.assign(route);
            }
        </script>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">
                            Datos del incidente
                        </h4>
                    </div>
                    <div class="modal-body">

                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th class="text-center">Usuario</th>
                                <th class="text-center">Categoria</th>
                                <th class="text-center">Asunto</th>
                                <th class="text-center">Descripcion</th>
                                <th class="text-center">Serial</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td class="text-center">
                                    <span id="usuario"></span>
                                </td>
                                <td class="text-center">
                                    <span id="categoria"></span>
                                </td>
                                <td class="text-center">
                                    <span id="asunto"></span>
                                </td>
                                <td class="text-center">
                                    <span id="descripcion"></span>
                                </td>
                                <td class="text-center">
                                    <span id="serial"></span>
                                </td>
                            </tr>
                            </tbody>
                        </table>

                        <h4>Elemento afectado <br>
                            <span id="elemento" style="color: blue"></span></h4>
                        <h4>
                            hora : <span id="hora" style="color: blue"></span>
                            <br>
                            fecha : <span id="fecha" style="color: blue"></span>
                        </h4>
                    </div>
                    <div class="modal-footer">
                        <button class="btn bgm-deeporange waves-effect" data-dismiss="modal">
                            Cerrar
                        </button>

                        {% if user.is_superuser %}
                            <a onclick="SolucionarProblema()" class="btn bgm-lightgreen waves-effect">
                                Agregar una solucion
                            </a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="card">
            <div class="card-header">
                <h2>
                    {% if incidentes_lista %}
                        No hay incidentes registrados hasta el momento
                    {% else %}
                        Este elemento de configuracion no tiene incidentes registrados
                    {% endif %}
                    <br>
                    <button onclick="goBack()" class="btn bgm-teal pull-right waves-effect">
                        <i class="zmdi zmdi-arrow-left zmdi-hc-fw"></i> Volver
                    </button>
                </h2>
            </div>
        </div>
    {% endif %}
    {% if incidentes_lista %}
        {% if user.is_superuser %}
            <a href="{% url 'soporte:crear_incidente' %}"
               class="btn btn-float bgm-indigo m-btn waves-effect waves-circle waves-float">
                <i class="zmdi zmdi-plus"></i>
            </a>
        {% else %}
            <a href="{% url 'empleado:crear_incidente' %}"
               class="btn btn-float bgm-indigo m-btn waves-effect waves-circle waves-float">
                <i class="zmdi zmdi-plus"></i>
            </a>
        {% endif %}
    {% else %}
        <a href="{% url 'soporte:incidente_elemento' elemento.id %}"
           class="btn btn-float bgm-blue m-btn waves-effect waves-circle waves-float">
            <i class="zmdi zmdi-plus"></i>
        </a>
    {% endif %}
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}

templates/listados/soporte/marcas.html
{% extends 'Main/base.html' %}

{% block contenido %}

    <div class="card">
        <div class="card-header">
            <h2>
                Lista de proveedores
            </h2>
        </div>

        <div class="table-responsive">
            <table id="data-table-basic" class="table table-striped">
                <thead>
                <tr>
                    <th class="text-center">
                        id
                    </th>
                    <th class="text-center">
                        nombre
                    </th>
                    <th class="text-center">
                        acciones
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for elemento in proveedores %}
                    <tr>
                        <td>{{ elemento.id }}</td>
                        <td>{{ elemento.nombre }}</td>
                        <td>
                            <a href="{% url 'soporte:editar_marca' elemento.id %}"
                               class="btn bgm-cyan waves-effect">
                                editar <i class="zmdi zmdi-pencil"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    <a href="{% url 'soporte:crear_marca' %}"
       class="btn btn-float btn-success m-btn waves-effect waves-circle waves-float">
        <i class="zmdi zmdi-plus"></i>
    </a>

    {% if is_paginated %}
        {% include 'Main/paginator.html' %}
    {% endif %}

{% endblock %}

templates/listados/soporte/proveedores.html
{% extends 'Main/base.html' %}

{% block contenido %}

    <div class="card">
        <div class="card-header">
            <h2>
                Lista de proveedores
            </h2>
        </div>

        <div class="table-responsive">
            <table id="data-table-basic" class="table table-striped">
                <thead>
                <tr>
                    <th class="text-center">
                        id
                    </th>
                    <th class="text-center">
                        nombre
                    </th>
                    <th class="text-center">
                        acciones
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for elemento in proveedores %}
                    <tr>
                        <td>{{ elemento.id }}</td>
                        <td>{{ elemento.nombre }}</td>
                        <td>
                            <a href="{% url 'ajustes:p_p' elemento.id %}"
                               class="btn bgm-teal waves-effect">
                                productos <i class="zmdi zmdi-puzzle-piece"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    <a href="{% url 'soporte:crear_proveedor' %}"
       class="btn btn-float btn-success m-btn waves-effect waves-circle waves-float">
        <i class="zmdi zmdi-plus"></i>
    </a>

    {% if is_paginated %}
        {% include 'Main/paginator.html' %}
    {% endif %}

{% endblock %}

templates/listados/soporte/soluciones.html
{% extends 'Main/base.html' %}

{% block contenido %}

    <div class="card">
        <div class="card-header">
            <h2>
                {% if soluciones.count > 0 %}
                    Soluciones del {{ incidente }} : {{ incidente.elemento_afectado }}
                    <br>
                    <strong style="color: darkslategrey">
                        este incidente cuenta con
                        <span style="color: coral">{{ soluciones.count }}</span>
                        {% if soluciones.count == 1 %}
                            solucion
                        {% else %}
                            soluciones
                        {% endif %}

                    </strong>
                {% else %}
                    El {{ incidente }}
                    <strong>
                        no tiene soluciones
                    </strong>
                    {% if user.is_superuser %}
                        <strong>
                            , desea crear una?
                        </strong>
                        <br><br>
                        <a href="{% url 'soporte:crear_solucion' incidente.id %}"
                           class="btn bgm-green waves-effect">
                            si, deseo crear una solucion para el {{ incidente }}
                        </a>
                        <button onclick="goBack()" class="btn bgm-orange waves-effect">
                            No, gracias
                        </button>
                    {% endif %}
                {% endif %}
            </h2>
        </div>

        {% if soluciones.count > 0 %}
            <div class="table-responsive">
                <table id="data-table-basic" class="table table-striped">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>Incidente</th>
                        <th>Elemento Afectado</th>
                        <th>Descripcion</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for elemento in soluciones %}
                        <tr>
                            <td>{{ elemento.id }}</td>
                            <td>{{ elemento.incidente }}</td>
                            <td>
                                {{ elemento.elemento_afectado.tipo }}
                                {{ elemento.elemento_afectado.descripcion }}
                            </td>
                            <td>{{ elemento.descripcion }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        {% endif %}

    </div>

    {% if request.user.is_superuser %}
        <a href="{% url 'soporte:crear_solucion' incidente.id %}" class="btn btn-float btn-success m-btn waves-effect waves-circle waves-float">
            <i class="zmdi zmdi-plus"></i>
        </a>
    {% endif %}

    {% if is_paginated %}
        {% include 'Main/paginator.html' %}
    {% endif %}

{% endblock %}